version: "3.8"
services:   
  app:      
    container_name: bagel-backend    
    restart: unless-stopped      
    build: 
      context: ./backend
      dockerfile: Backend.dockerfile   
    ports:         
      - '8080:8080'      
    links:         
      - mongodb  
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./init-mongodb/data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
