version: "3"
services:   
  app:      
    container_name: bagel-backend    
    restart: always      
    build: 
      context: ./backend
      dockerfile: Backend.dockerfile   
    ports:         
      - '8080:3000'      
    links:         
      - mongo  
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    # env_file:
    #   - .env # 환경변수로 사용할 파일
    
  db:      
    container_name: mongo      
    image: mongo      
    ports:         
      - '8081:8081'
# services:
# frontend:
#     image: awesome/webapp
#     ports:
#       - "443:8043"
#     networks:
#       - front-tier
#       - back-tier
#     configs:
#       - httpd-config
#     secrets:
#       - server-certificate

#   backend:
#     image: awesome/database
#     volumes:
#       - db-data:/etc/data
#     networks:
#       - back-tier
#   mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://localhost/
