name: bagel-frontend

on:
    # start pipeline when merged
    # pull_request:
    #     branches: [ frontend ]
    #     types: [ closed ]
    push: 
        branches: [Adopt_github_action#193]
jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '16'
            
            - name: Setup Angular
              run: |
               cd frontend
               npm install -g @angular/cli@15.0.4 
               npm install
               ng build

            
            # - name: Install dependencies
            #   run: npm install
        
            # - name: Build Angular Application
            #   run: ng build --prod
        
            - name: Archive artifacts
              uses: actions/upload-artifact@v3
              with:
                name: build-files
                path: ${{ github.workspace }}/frontend
                if-no-files-found: error
              #run: ng build
    # build:
    #     needs: setup
    #     runs-on: ubuntu-latest

    # test: 
    #     needs: setup
    #     runs-on: self-hosted

    #     steps: 
    #         - run: ng version
