name: bagel-frontend

on:
    # start pipeline when merged
    # pull_request:
    #     branches: [ frontend ]
    #     types: [ closed ]
    push: 
        branches: [Adopt_github_action#193]
jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '16'
            
            - name: Setup Angular
              run: npm install -g @angular/cli && npm ci

            - name: Build Frontend
              run: ng build
    # build:
    #     needs: setup
    #     runs-on: ubuntu-latest

    # test: 
    #     needs: setup
    #     runs-on: self-hosted

    #     steps: 
    #         - run: ng version
