name: bagel-frontend

on:
    # start pipeline when merged
    pull_request:
        branches: [ frontend ]
        types: [ closed ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '16'
            
            - run: npm ci
            - run: npm test
